language: go
go:
    - 1.11
    - tip
script:
    - go get github.com/mattn/goveralls
    - go get -t ./...
    - make
    - $GOPATH/bin/goveralls -service=travis-ci
before_deploy:
    - make VERSION=${TRAVIS_TAG} release -j2
deploy:
    provider: releases
    api_key:
        secure:
    file: release/*
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
